#This file will contain the MySQL deployment and service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0                       # Use the appropriate MySQL version
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mahmoud"                  # Set your root password
            - name: MYSQL_DATABASE
              value: "achatdb"                  # Set database name
            - name: MYSQL_USER
              value: "achatuser"                # Set database user
            - name: MYSQL_PASSWORD
              value: "achatpassword"            # Set user password
              # Set user password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306            # MySQL's port
      targetPort: 3306
  type: ClusterIP          # Set to ClusterIP for internal access
