version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mahmoud               # Root password
      MYSQL_DATABASE: achatdb                 # Database name
      MYSQL_USER: root                             # Database user
      MYSQL_PASSWORD: mahmoud                    # User password
    ports:
      - "3307:3306"                                # Expose MySQL port
    volumes:
      - /home/mysql/data:/var/lib/mysql  # Use the correct host path                  # Persistent storage for data

  app:
    image: chaarimahmoud/tp_devops:latest           # Replace with your Docker image
    container_name: achat_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/achatdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mahmoud
    ports:
      - "8089:8089"                                    # Expose app port to localhost

volumes:
  mysql_data: